apiVersion: k3d.io/v1alpha5
kind: Simple 
metadata:
  name: home-media-server
servers: 1
agents: 0
image: k3d-cuda:latest
network: home-media-server
volumes:
  - volume: /mnt/c/home-media-server/config:/home-media-server/config
    nodeFilters:
      - server:0
      - agent:*
  - volume: /mnt/c/home-media-server/media:/home-media-server/media
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 8096:30096
    nodeFilters:
      - server:0
  - port: 8920:30097
    nodeFilters:
      - server:0
  - port: 7359:30098
    nodeFilters:
      - server:0
  - port: 1900:30099
    nodeFilters:
      - server:0
  - port: 7878:30100
    nodeFilters:
      - server:0
  - port: 8989:30101
    nodeFilters:
      - server:0
  - port: 9091:30102
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
          - agent:*
    nodeLabels:
      - label: nvidia.com/gpu.present=true
        nodeFilters:
          - server:0
          - agent:*
    
  runtime:
    gpuRequest: all
    labels: []