version: "3.8"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --log.level=$TRAEFIK_LOG_LEVEL
      - --api
      - --api.dashboard
      - --api.insecure
      - --providers.docker
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - 80:80
      - 8080:8080
    labels:
      - traefik.enable=false

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    labels:
      - traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)
      - traefik.http.middlewares.portainer-prefix-to-port.redirectregex.regex=^$DOMAIN/portainer$$
      - traefik.http.middlewares.portainer-prefix-to-port.redirectregex.replacement=$DOMAIN:9000
      - traefik.http.routers.portainer.middlewares=portainer-prefix-to-port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $MOUNT/appdata/portainer:/data
      - $MOUNT/shared:/shared
    environment:
      - TZ=$TZ
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
    labels:
      - traefik.http.routers.transmission.rule=PathPrefix(`/transmission`)
      - traefik.http.middlewares.transmission-prefix-to-port.redirectregex.regex=^$DOMAIN/transmission$$
      - traefik.http.middlewares.transmission-prefix-to-port.redirectregex.replacement=$DOMAIN:9091
      - traefik.http.routers.transmission.middlewares=transmission-prefix-to-port
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/appdata/transmission:/config
      - $MOUNT/downloads:/downloads
      - $MOUNT/shared:/shared
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    labels:
      - traefik.http.routers.jackett.rule=PathPrefix(`/jackett`)
      - traefik.http.middlewares.jackett-prefix-to-port.redirectregex.regex=^$DOMAIN/jackett$$
      - traefik.http.middlewares.jackett-prefix-to-port.redirectregex.replacement=$DOMAIN:9117
      - traefik.http.routers.jackett.middlewares=jackett-prefix-to-port
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/appdata/jackett:/config
      - $MOUNT/downloads:/downloads
      - $MOUNT/shared:/shared

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    labels:
      - traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)
      - traefik.http.middlewares.radarr-prefix-to-port.redirectregex.regex=^$DOMAIN/radarr$$
      - traefik.http.middlewares.radarr-prefix-to-port.redirectregex.replacement=$DOMAIN:7878
      - traefik.http.routers.radarr.middlewares=radarr-prefix-to-port
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/downloads:/downloads
      - $MOUNT/appdata/radarr:/config
      - $MOUNT/movies:/movies
      - $MOUNT/shared:/shared

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    ports:
      - 8989:8989
    labels:
      - traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)
      - traefik.http.middlewares.sonarr-prefix-to-port.redirectregex.regex=^$DOMAIN/sonarr$$
      - traefik.http.middlewares.sonarr-prefix-to-port.redirectregex.replacement=$DOMAIN:8989
      - traefik.http.routers.sonarr.middlewares=sonarr-prefix-to-port
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/downloads:/downloads
      - $MOUNT/appdata/sonarr:/config
      - $MOUNT/tv:/tv
      - $MOUNT/shared:/shared

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/appdata/bazarr:/config
      - $MOUNT/movies:/movies
      - $MOUNT/tv:/tv
      - $MOUNT/shared:/shared
    ports:
      - 6767:6767
    labels:
      - traefik.http.routers.bazarr.rule=PathPrefix(`/bazarr`)
      - traefik.http.middlewares.bazarr-prefix-to-port.redirectregex.regex=^$DOMAIN/bazarr$$
      - traefik.http.middlewares.bazarr-prefix-to-port.redirectregex.replacement=$DOMAIN:6767
      - traefik.http.routers.bazarr.middlewares=bazarr-prefix-to-port
    restart: unless-stopped
