version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/plex/config:/config
      - ${MOUNT}/appdata/plex/transcode:/transcode
      - ${MOUNT}/movies:/libraries/movies
      - ${MOUNT}/tv:/libraries/tv
      - ${MOUNT}/shared:/shared

  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - --api
      - --api.dashboard
      - --api.insecure # Don't do that in production
      - --providers.docker
      # - --entrypoints.websecure.address=:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    ports:
      - 8989:8989
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - traefik.enable=false

  portainer:
    image: portainer/portainer
    container_name: portainer
    # ports:
    #   - 9000:9000
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.backend=portainer
      - traefik.passHostHeader=true
      - traefik.http.routers.portainer.rule=Path(`/portainer`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MOUNT}/appdata/portainer:/data
      - ${MOUNT}/shared:/shared
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    labels:
      - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
    labels:
      - traefik.http.routers.transmission.rule=PathPrefix(`/transmission`)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    labels:
      - traefik.http.routers.jackett.rule=PathPrefix(`/jackett`)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    labels:
      - traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/radarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/shared:/shared

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    # ports:
    #   - 8989:8989
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.sonarr.rule=Path(`/sonarr`)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/sonarr:/config
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared

  tautulli:
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    ports:
      - 8181:8181
    labels:
      - traefik.http.routers.tautulli.rule=PathPrefix(`/tautulli`)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/tautulli:/config
      - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
      - ${MOUNT}/shared:/shared

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/bazarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared
    ports:
      - 6767:6767
    labels:
      - traefik.http.routers.bazarr.rule=PathPrefix(`/bazarr`)
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true