version: "3.8"
services:
  plex:
    image: linuxserver/plex:bionic
    restart: unless-stopped
    container_name: plex
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp # being use by avahi-daemon, seems to be unneeded.
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    devices:
      # mounts the GPU on the host which is needed for hardware transcoding.
      # Wont do anythign on PI 4 as plex doesn't transcode on anything other than Intel quicksync, but will throw on oearlier PI versions
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/plex/config:/config
      - ${MOUNT}/appdata/plex/transcode:/transcode
      - ${MOUNT}/shared:/shared

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/radarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/shared:/shared

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/sonarr:/config
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared

  tautulli:
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/tautulli:/config
      - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
      - ${MOUNT}/shared:/shared

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/bazarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared
    ports:
      - 6767:6767
    restart: unless-stopped
