version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    networks:
      - traefik_proxy
    volumes:
      - $MOUNT/appdata/plex/config:/config
      - $MOUNT/appdata/plex/transcode:/transcode
      - $MOUNT/movies:/libraries/movies
      - $MOUNT/tv:/libraries/tv
      - $MOUNT/shared:/shared
    labels:
      - traefik.enable=true

      # remote
      - traefik.http.routers.plex-remote.entrypoints=https
      - traefik.http.routers.plex-remote.rule=Host(`plex.$DOMAIN`)
      - traefik.http.routers.plex-remote.middlewares=chain-oauth
      - traefik.http.routers.plex-remote.service=plex-svc
      - traefik.http.services.plex-svc.loadbalancer.server.port=32400

      # local
      - traefik.http.routers.plex-local.rule=PathPrefix(`/plex`)
      - traefik.http.middlewares.plex-prefix-to-port.redirectregex.regex=^$DOMAIN/plex$$
      - traefik.http.middlewares.plex-prefix-to-port.redirectregex.replacement=$DOMAIN:9000
      - traefik.http.routers.plex-local.middlewares=plex-prefix-to-port

  tautulli:
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    ports:
        - 8181:8181
    labels:
      - traefik.enable=true

      # remote
      - traefik.http.routers.tautulli-remote.entrypoints=https
      - traefik.http.routers.tautulli-remote.rule=Host(`tautulli.$DOMAIN`)
      - traefik.http.routers.tautulli-remote.middlewares=chain-oauth
      - traefik.http.routers.tautulli-remote.service=tautulli-svc
      - traefik.http.services.tautulli-svc.loadbalancer.server.port=8181

      # local
      - traefik.http.routers.tautulli-local.rule=PathPrefix(`/tautulli`)
      - traefik.http.middlewares.tautulli-prefix-to-port.redirectregex.regex=^$DOMAIN/tautulli$$
      - traefik.http.middlewares.tautulli-prefix-to-port.redirectregex.replacement=$DOMAIN:8181
      - traefik.http.routers.tautulli-local.middlewares=tautulli-prefix-to-port
    environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=$TZ
    restart: unless-stopped
    volumes:
        - $MOUNT/appdata/tautulli:/config
        - $MOUNT/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
        - $MOUNT/shared:/shared
