version: "3.8"
services:
  plex:
    image: linuxserver/plex:bionic
    restart: unless-stopped
    container_name: plex
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp # being use by avahi-daemon, seems to be unneeded.
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    devices:
      # mounts the GPU on the host which is needed for hardware transcoding.
      # Wont do anythign on PI 4 as plex doesn't transcode on anything other than Intel quicksync, but will throw on oearlier PI versions
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/plex/config:/config
      - ${MOUNT}/appdata/plex/transcode:/transcode

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/radarr:/config
      - ${MOUNT}/movies:/movies

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/sonarr:/config
      - ${MOUNT}/tv:/tv

  # tautulli:
  #   image: linuxserver/tautulli:latest
  #   restart: unless-stopped
  #   container_name: tautulli
  #   extra_hosts: *pi
  #   ports:
  #     # Host port 8181 is mapped to container port 8181
  #     - "8181:8181"
  #   environment:
  #     # The container is run as the user with this PUID and PGID (user and group id).
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     # config directory
  #     - ${MOUNT}/appdata/tautulli:/config
  #     # Tautulli needs access to plex logs. In the plex container we mounted ${MOUNT}/appdata/plex of the host as the
  #     # config directory for plex. Logs are located within this config directory
  #     - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
