version: "3.8"
services:
  plex:
    image: linuxserver/plex:bionic
    restart: unless-stopped
    container_name: plex
    networks:
      - default
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp # being use by avahi-daemon, seems to be unneeded.
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    devices:
      # mounts the GPU on the host which is needed for hardware transcoding.
      # Wont do anythign on PI 4 as plex doesn't transcode on anything other than Intel quicksync, but will throw on oearlier PI versions
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/plex/config:/config
      - ${MOUNT}/appdata/plex/transcode:/transcode
      - ${MOUNT}/shared:/shared

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    networks:
      - default
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    networks:
      - default
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/radarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/shared:/shared

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    networks:
      - default
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/sonarr:/config
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared

  tautulli:
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/tautulli:/config
      - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
      - ${MOUNT}/shared:/shared

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/bazarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared
    ports:
      - 6767:6767
    restart: unless-stopped

  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
