version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/plex/config:/config
      - ${MOUNT}/appdata/plex/transcode:/transcode
      - ${MOUNT}/movies:/libraries/movies
      - ${MOUNT}/tv:/libraries/tv
      - ${MOUNT}/shared:/shared

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MOUNT}/appdata.portainer:/data
      - ${MOUNT}/shared:/shared
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/shared:/shared

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/radarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/shared:/shared

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/appdata/sonarr:/config
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared

  tautulli:
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/tautulli:/config
      - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
      - ${MOUNT}/shared:/shared

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/bazarr:/config
      - ${MOUNT}/movies:/movies
      - ${MOUNT}/tv:/tv
      - ${MOUNT}/shared:/shared
    ports:
      - 6767:6767
    restart: unless-stopped
