version: "3"
x-extra_hosts:
  # This is added so that within each service you can communicate to another service by using the DNS name of pi rather
  # than using IP address. Makes it easy if the IP address changes. For example, when configuring Radarr, you can
  # configure the transmission client url as http://pi:9091
  &pi
  # Change this to IP of your RPi
  - "pi:192.168.1.74"
services:
  plex:
    image: linuxserver/plex:bionic
    restart: always
    container_name: plex
    network_mode: host
    extra_hosts: *pi
    devices:
      # mounts the GPU on the host which is needed for hardware transcoding. Wont do anythign on PI 4 as plex doesn't transcode on anythgin other than Intel quicksync. Delete if on any other PI version.
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # Docker bind mounts are used to store config and media on the host's filesystem. Config for plex will be stored
      # in ${MOUNT}/appdata/plex/config directory and any transcoding data is stored in a transcode directory
      - ${MOUNT}/appdata/plex/config:/config # configuration
      - ${MOUNT}/appdata/plex/transcode:/transcode # transcoding data
      # Within plex, we are mounting the root of ${MOUNT} to /all_media directory. So within plex, when you look
      # inside /all_media directory you would see the same file structure as ${MOUNT} on the host
      - ${MOUNT}:/all_media # 

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/transmission:/config
      - ${MOUNT}/downloads:/downloads
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOUNT}/appdata/jackett:/config
      - ${MOUNT}/downloads:/downloads

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # Radarr needs to know where the downloaded media is. This is told to radarr by transmission
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/downloads:/data
      # config directory
      - ${MOUNT}/appdata/radarr:/config
      # Movies imported by radarr are stored in ${MOUNT}/movies directory on the host. Radarr sees this directory
      # as /movies. Within radarr make your root folder as /movies
      - ${MOUNT}/movies:/movies

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # sonarr needs to know where the downloaded media is. This is told to sonarr by transmission
      - ${MOUNT}/downloads:/downloads
      - ${MOUNT}/downloads:/data
      # config directory
      - ${MOUNT}/appdata/sonarr:/config
      # TV shows imported by sonarr are stored in ${MOUNT}/tv directory on the host. sonarr sees this directory
      # as /tv. Within sonarr make your root folder as /tv
      - ${MOUNT}/tv:/tv

  # tautulli:
  #   image: linuxserver/tautulli:latest
  #   restart: unless-stopped
  #   container_name: tautulli
  #   extra_hosts: *pi
  #   ports:
  #     # Host port 8181 is mapped to container port 8181
  #     - "8181:8181"
  #   environment:
  #     # The container is run as the user with this PUID and PGID (user and group id).
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     # config directory
  #     - ${MOUNT}/appdata/tautulli:/config
  #     # Tautulli needs access to plex logs. In the plex container we mounted ${MOUNT}/appdata/plex of the host as the
  #     # config directory for plex. Logs are located within this config directory
  #     - ${MOUNT}/appdata/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
