version: "3.8"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $MOUNT/appdata/jellyfin:/config
      - $MOUNT/tv:/data/tvshows
      - $MOUNT/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-remote.entrypoints=https
      - traefik.http.routers.jellyfin-remote.rule=Host(`jellyfin.$DOMAIN`)
      - traefik.http.routers.jellyfin-remote.middlewares=chain-oauth
      - traefik.http.routers.jellyfin-remote.service=jellyfin-svc
      - traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096
    devices:
      - /dev/vcsm-cma:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    restart: unless-stopped
