version: '3'

includes:
  infrastructure:
    taskfile: infrastructure/Taskfile.yml
    dir: infrastructure
  helm:
    taskfile: helm/Taskfile.yml
    dir: helm
  k3d:
    taskfile: .k3d/Taskfile.yml
    dir: .k3d

tasks:
  check-dependencies:
    deps:
      - task: infrastructure:check-dependencies
      - task: helm:check-dependencies
      - task: k3d:check-dependencies

  full-recreate:
    desc: |
      Teardown an existing cluster if exists
      Rebuild cluster image
      Initialise Terraform
      Create a new cluster
      Apply the infrastructure state
      Create a helm release
    deps:
      - task: k3d:delete-cluster
        silent: true
    cmds:
      - task: infrastructure:init
      - task: k3d:build-image
      - task: k3d:create-cluster
      - task: infrastructure:apply
      - task: helm:release


