version: '3'

includes:
  infrastructure:
    taskfile: infrastructure/Taskfile.yml
    dir: infrastructure
  helm:
    taskfile: helm/Taskfile.yml
    dir: helm
  k3d:
    taskfile: .k3d/Taskfile.yml
    dir: .k3d

tasks:
  dependencies:check:
    deps:
      - task: infrastructure:dependencies:check
      - task: helm:dependencies:check
      - task: k3d:dependencies:check

  recreate:
    desc: |
      Teardown an existing cluster if exists.
      Rebuild cluster image.
      Initialise Terraform.
      Create a new cluster.
      Apply the infrastructure state.
      Create a helm release.
    deps:
      - task: k3d:cluster:delete
        silent: true
    cmds:
      - task: infrastructure:init
      - task: k3d:image:build
      - task: k3d:cluster:create
      - task: infrastructure:apply
        vars:
          CLI_ARGS: $INFRASTRUCTURE_APPLY_ARGS
      - task: helm:dependencies:build
      - task: helm:release


