version: '3.9'
services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-media-server-github-runner
    environment:
      TOKEN: ${TOKEN}
      REPOSITORY_URL: ${REPOSITORY_URL}
    volumes:
      - ${KUBE_CONFIG_PATH}:/home/githubrunner/.kube/config
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    restart: always
