apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
spec:
  clusterIP: {{ .Values.bazarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.bazarr.ports.http }}
    targetPort: {{ .Values.bazarr.ports.http }}
    protocol: TCP
  selector:
    app: bazarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: {{ include "image" .Values.bazarr.image }}
        imagePullPolicy: {{ .Values.bazarr.image.pullPolicy }}
        name: bazarr
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: bazarr
          - name: media
            mountPath: movies
            subPath: movies
          - name: media
            mountPath: tv
            subPath: tv
        ports:
          - containerPort: {{ .Values.bazarr.ports.http }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.bazarr.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
