apiVersion: v1
kind: Service
metadata:
  name: calibre-service
spec:
  clusterIP: {{ .Values.calibre.clusterIP }}
  ports:
  - port: 80
    protocol: TCP
    name: nginx
  selector:
    app: calibre
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calibre-nginx-config
data:
  nginx.conf: |
    events{
    }
    http {
      server {
        client_max_body_size 20M;
        location /calibre {
          add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
          proxy_pass              http://localhost:8083;
          proxy_set_header        Host                    $http_host;
          proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
          proxy_set_header        X-Scheme                https;
          proxy_busy_buffers_size 1024k;
          proxy_buffers   				4                       512k;
          proxy_buffer_size   		1024k;
          proxy_set_header        X-Script-Name           /calibre; 
        }

        location = /robots.txt {
          add_header              Content-Type            text/plain;
          return 200              "User-agent: *\nDisallow: /\n";
        }
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: nginx-config-volume
          configMap:
            name: calibre-nginx-config
      containers:
        - name: nginx
          image: {{ include "image" .Values.calibre.nginx.image }}
          imagePullPolicy: {{ .Values.calibre.nginx.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.Timezone }}
            - name: PUID
              value: "{{ .Values.PUID }}"
            - name: PGID
              value: "{{ .Values.PGID }}"
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.calibre.web.image }}
          imagePullPolicy: {{ .Values.calibre.web.image.pullPolicy }}
          name: calibre-web
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /books
              subPath: books
            - name: config
              mountPath: /config
              subPath: calibre-web
