apiVersion: v1
kind: Service
metadata:
  name: calibre-service
spec:
  ports:
  - port: 80
    protocol: TCP
    name: nginx
  - port: 8083
    protocol: TCP
    name: calibre-web-ui
  selector:
    app: calibre
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  calibre.conf: |
    server {
      client_max_body_size 20M;
      location /calibre {
          proxy_bind              $server_addr;
          proxy_pass              http://localhost:8083;
          proxy_set_header        Host            $http_host;
          proxy_set_header        X-Script-Name   /calibre;
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: {{ include "image" .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.Timezone }}
            - name: PUID
              value: "{{ .Values.PUID }}"
            - name: PGID
              value: "{{ .Values.PGID }}"
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/calibre.conf
              subPath: calibre.conf
          ports:
            - containerPort: 80
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.calibreweb.image }}
          imagePullPolicy: {{ .Values.calibreweb.image.pullPolicy }}
          name: calibre-web
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /books
              subPath: books
            - name: config
              mountPath: /config
              subPath: calibre-web
