apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: heimdall
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: linuxserver/heimdall:2.5.6
        name: radarr
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: heimdall
        ports:
        - containerPort: 80