apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  clusterIP: {{ .Values.heimdall.clusterIP }}
  ports:
  - port: {{ .Values.heimdall.ports.http }}
    protocol: TCP
  selector:
    app: heimdall
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: {{ include "image" .Values.heimdall.image }}
        name: heimdall
        imagePullPolicy: {{ .Values.heimdall.image.pullPolicy }}
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: heimdall
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.heimdall.ports.http }}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.heimdall.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        ports:
        - containerPort: {{ .Values.heimdall.ports.http }}