apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
spec:
  clusterIP: 10.43.178.128
  ports:
  - port: 80
    protocol: TCP
    name: nginx
  selector:
    app: homeassistant
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-nginx-config
data:
  nginx.conf: |
    events{
    }
    http {
      server {
        location / {
          proxy_pass http://localhost:8123/;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_http_version 1.1;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: nginx-config-volume
          configMap:
            name: homeassistant-nginx-config
      containers:
        - name: nginx
          image: {{ include "image" .Values.nginx.image }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.Timezone }}
            - name: PUID
              value: "{{ .Values.PUID }}"
            - name: PGID
              value: "{{ .Values.PGID }}"
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.homeassistant.image }}
          imagePullPolicy: {{ .Values.homeassistant.image.pullPolicy }}
          name: homeassistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: homeassistant
