apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
spec:
  ports:
  - port: 8123
    protocol: TCP
  selector:
    app: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-node-port
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      name: http
      port: 8123
      targetPort: 8123
      nodePort: 30103
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: {{ include "image" .Values.homeassistant.image }}
        imagePullPolicy: {{ .Values.homeassistant.image.pullPolicy }}
        name: homeassistant
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: homeassistant
        ports:
        - containerPort: 8123