apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
spec:
  clusterIP: {{ .Values.homeassistant.clusterIP }}
  ports:
  - name: http
    port: 8123
    targetPort: 8123
    protocol: TCP
  selector:
    app: homeassistant
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.homeassistant.image }}
          imagePullPolicy: {{ .Values.homeassistant.image.pullPolicy }}
          name: homeassistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: homeassistant
