apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp-service
spec:
  ports:
    - name: http
      port: 8096
      protocol: TCP
      targetPort: 8096
    - name: https
      port: 8920
      protocol: TCP
      targetPort: 8920
  selector:
    app: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-udp-service
spec:
  ports:
    - name: auto-discovery-1
      port: 7359
      protocol: UDP
      targetPort: 7359
    - name: auto-discovery-2
      port: 1900
      protocol: UDP
      targetPort: 1900
  selector:
    app: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-node-port
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      name: '8096'
      port: 8096
      targetPort: 8096
      nodePort: 30096
    - protocol: TCP
      name: '8920'
      port: 8920
      targetPort: 8920
      nodePort: 30097
    - protocol: UDP
      name: '7359'
      port: 7359
      targetPort: 7359
      nodePort: 30098
    - protocol: UDP
      name: '1900'
      port: 1900
      targetPort: 1900
      nodePort: 30099
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: media
          persistentVolumeClaim:
            claimName: media
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        image: {{ include "image" .Values.jellyfin.image }}
        imagePullPolicy: {{ .Values.jellyfin.image.pullPolicy }}
        resources:
          limits:
            nvidia.com/gpu: 1
        name: jellyfin
        ports:
          - containerPort: 8096
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: jellyfin
          - name: media
            mountPath: /movies
            subPath: movies
          - name: media
            mountPath: /tv
            subPath: tv