apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.storage.host.media.capacity }}
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.storage.host.media.dir }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists  # Can run on any node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.host.media.capacity }}