apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
spec:
  clusterIP: {{ .Values.prowlarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.prowlarr.ports.http }}
    targetPort: {{ .Values.prowlarr.ports.http }}
    protocol: TCP
  selector:
    app: prowlarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
      - name: flaresolverr
        env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: LOG_LEVEL
            value: debug
        image: {{ include "image" .Values.prowlarr.flaresolverr.image }}
        imagePullPolicy: {{ .Values.prowlarr.flaresolverr.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.prowlarr.flaresolverr.ports.http }}
      - name: prowlarr
        env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: {{ include "image" .Values.prowlarr.image }}
        imagePullPolicy: {{ .Values.prowlarr.image.pullPolicy }}

        volumeMounts:
          - name: config
            mountPath: /config
            subPath: prowlarr
        startupProbe:
          tcpSocket:
            port: {{ .Values.prowlarr.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /prowlarr/ping
            port: {{ .Values.prowlarr.ports.http }}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /prowlarr/ping
            port: {{ .Values.prowlarr.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        ports:
          - containerPort: {{ .Values.prowlarr.ports.http }}