apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
spec:
  clusterIP: {{ .Values.prowlarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.prowlarr.ports.http }}
    targetPort: {{ .Values.prowlarr.ports.http }}
    protocol: TCP
  selector:
    app: prowlarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
      - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: LOG_LEVEL
            value: debug
        image: {{ include "image" .Values.prowlarr.flaresolverr.image }}
        imagePullPolicy: {{ .Values.prowlarr.flaresolverr.image.pullPolicy }}
        name: transmissionopenvpn
        ports:
          - containerPort: {{ .Values.prowlarr.flaresolverr.ports.http }}
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: {{ include "image" .Values.prowlarr.image }}
        imagePullPolicy: {{ .Values.prowlarr.image.pullPolicy }}
        name: prowlarr
        volumeMounts:
          - name: config
            mountPath: /config
            subPath: prowlarr
        ports:
        - containerPort: {{ .Values.prowlarr.ports.http }}