apiVersion: v1
kind: Service
metadata:
  name: radarr-service
spec:
  clusterIP: {{ .Values.radarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.radarr.ports.http }}
    targetPort: {{ .Values.radarr.ports.http }}
    protocol: TCP
  selector:
    app: radarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.radarr.image }}
          imagePullPolicy: {{ .Values.radarr.image.pullPolicy }}
          name: radarr
          ports:
            - containerPort: {{ .Values.radarr.ports.http }}
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /movies
              subPath: movies
            - name: config
              mountPath: /config
              subPath: radarr
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:{{ .Values.radarr.ports.http }}/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:{{ .Values.radarr.ports.http }}/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
