apiVersion: v1
kind: Service
metadata:
  name: readarr-service
spec:
  clusterIP: {{ .Values.readarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.readarr.ports.http }}
    targetPort: {{ .Values.readarr.ports.http }}
    protocol: TCP
  selector:
    app: readarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
        - env:
          - name: TZ
            value: {{ .Values.Timezone }}
          - name: PUID
            value: "{{ .Values.PUID }}"
          - name: PGID
            value: "{{ .Values.PGID }}"
          resources:
            limits:
              memory: 1Gi
          image: {{ include "image" .Values.readarr.image }}
          imagePullPolicy: {{ .Values.readarr.image.pullPolicy }}
          name: readarr
          ports:
            - containerPort: {{ .Values.readarr.ports.http }}
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /books
              subPath: books
            - name: config
              mountPath: /config
              subPath: readarr
