apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
spec:
  clusterIP: 10.43.26.211
  ports:
  - name: http
    port: 8989
    targetPort: 8989
    protocol: TCP
  selector:
    app: sonarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            memory: 1Gi
        image: {{ include "image" .Values.sonarr.image }}
        imagePullPolicy: {{ .Values.sonarr.image.pullPolicy }}
        name: sonarr
        ports:
          - containerPort: 8989
        volumeMounts:
          - name: media
            mountPath: /downloads
            subPath: downloads
          - name: media
            mountPath: /tv
            subPath: tv
          - name: config
            mountPath: /config
            subPath: sonarr
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl "http://localhost:8989/sonarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 30
          periodSeconds: 10