apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
spec:
  clusterIP: {{ .Values.sonarr.clusterIP }}
  ports:
  - name: http
    port: {{ .Values.sonarr.ports.http }}
    targetPort: {{ .Values.sonarr.ports.http }}
    protocol: TCP
  selector:
    app: sonarr
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: "{{ .Values.PUID }}"
        - name: PGID
          value: "{{ .Values.PGID }}"
        resources:
          limits:
            memory: 1Gi
        image: {{ include "image" .Values.sonarr.image }}
        imagePullPolicy: {{ .Values.sonarr.image.pullPolicy }}
        name: sonarr
        ports:
          - containerPort: {{ .Values.sonarr.ports.http }}
        volumeMounts:
          - name: media
            mountPath: /downloads
            subPath: downloads
          - name: media
            mountPath: /tv
            subPath: tv
          - name: config
            mountPath: /config
            subPath: sonarr
        startupProbe:
          tcpSocket:
            port: {{ .Values.sonarr.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /sonarr/ping
            port: {{ .Values.sonarr.ports.http }}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /sonarr/ping
            port: {{ .Values.sonarr.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1