apiVersion: v1
kind: Service
metadata:
  name: transmission-service
spec:
  clusterIP: {{ .Values.transmission.clusterIP }}
  ports:
  - name: transmission
    port: {{ .Values.transmission.ports.http }}
    targetPort: {{ .Values.transmission.ports.http }}
    protocol: TCP
  selector:
    app: transmission
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-scripts
data:
  stop-torrents-when-gluetun-unhealthy.sh: |
    #!/bin/sh
    while true; do
      if nc -z -v -w5 127.0.0.1 {{ .Values.gluetun.ports.healthcheck }}; then
        echo "Gluetun is healthy, starting all torrents"
        transmission-remote --torrent all --start
      else
        echo "Gluetun is unhealthy, stopping all torrents"
        transmission-remote --torrent all --stop
      fi
      sleep 10
    done
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: scripts
          configMap:
            name: transmission-scripts
            defaultMode: 0777
      containers:
        - name: gluetun
          image: {{ include "image" .Values.gluetun.image }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: {{ .Values.vpn.provider.name }}
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.vpn.auth.secret.keys.wireguard_private_key }}
                  name: {{ .Values.vpn.auth.secret.name }}
            {{- range .Values.vpn.provider.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.gluetun.ports.http }}
          volumeMounts:
            - name: config
              mountPath: /gluetun
              subPath: gluetun
        - name: transmission
          image: {{ include "image" .Values.transmission.image }}
          env:
            - name: TZ
              value: {{ .Values.Timezone }}
            - name: PUID
              value: "{{ .Values.PUID }}"
            - name: PGID
              value: "{{ .Values.PGID }}"
            - name: TRANSMISSION_WEB_UI
              value: {{ .Values.transmission.webui }}
            - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
              value: 'true'
            - name: TRANSMISSION_INCOMPLETE_DIR
              value: /downloads/incomplete
            - name: TRANSMISSION_WATCH_DIR_ENABLED
              value: 'true'
            - name: TRANSMISSION_WATCH_DIR
              value: /downloads/torrents
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads/complete
          ports:
            - containerPort: {{ .Values.transmission.ports.http }}
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: config
              mountPath: /config
              subPath: transmission
        - name: transmission-monitor
          image: {{ include "image" .Values.transmission.image }}
          command: ["/bin/sh", "-c"]
          args:
            - /scripts/stop-torrents-when-gluetun-unhealthy.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
