apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-server

commonLabels:
  app: home-server

resources:
- namespace.yml
- radarr.yml
- ingress.yml

patchesStrategicMerge:
- volumes_patch.yml
# - env_variables_patch.yaml

vars:
  - name: RADARR
    objref:
      kind: Service
      name: radarr
      apiVersion: v1