apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      volumes: 
      - hostPath: 
          path: /opt/home-media 
          type: DirectoryOrCreate 
        name: home-media