apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web-deployment
  labels:
    app: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: lscr.io/linuxserver/calibre-web
        ports:
        - containerPort: 8083
        env:
        - name: TZ
          value: Europ/London
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web-service
spec:
  selector:
    app: calibre-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083