apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Europ/London
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  selector:
    app: heimdall
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 90
    targetPort: 80