apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett-deployment
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: lscr.io/linuxserver/jackett
        ports:
        - containerPort: 9117
        env:
        - name: TZ
          value: Europ/London
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-service
spec:
  selector:
    app: jackett
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9117
    targetPort: 9117