apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-deployment
  labels:
    app: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
      - name: readarr
        image: linuxserver/readarr:nightly
        ports:
        - containerPort: 8787
        env:
        - name: TZ
          value: Europ/London
---
apiVersion: v1
kind: Service
metadata:
  name: readarr-service
spec:
  selector:
    app: readarr
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8787
    targetPort: 8787