apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: home-media-server
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        env:
          - name: TZ
            value: {{ .Values.TZ }}
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: home-media-server
spec:
  selector:
    app: heimdall
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31592