apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: home-media-server
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        env:
          - name: TZ
            value: {{ .Values.TZ }}
        ports:
        - containerPort: 8989

---

apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: home-media-server
spec:
  selector:
    app: jackett
  type: NodePort
  ports:
    - protocol: TCP
      port: 9117
      nodePort: 31589