version: '3'

env:
  VARIABLES_TFVARS_PATH: ../config/variables.tfvars

tasks:
  dependencies:check:
    preconditions:
      - sh: terraform version
        msg: Terraform must be installed
      - sh: az version
        msg: Azure CLI must be installed

  init:
    desc: Initialise terraform
    preconditions:
      - sh: az version
        msg: You must have the Azure CLI installed
      - sh: az account show
        msg: You must be logged in with the Azure CLI
    cmds:
      - terraform init {{.CLI_ARGS}}

  apply:
    desc: Apply infrastructure
    preconditions:
      - sh: k3d cluster list home-media-server
        msg: The home-media-server K3d cluster does not exist
      - sh: az account show
        msg: You must be logged in with the Azure CLI
      - sh: test -f $VARIABLES_TFVARS_PATH
        msg: "File must exist: $VARIABLES_TFVARS_PATH"
      
    cmds:
      - terraform apply -var-file=$VARIABLES_TFVARS_PATH {{.CLI_ARGS}}