apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
spec:
  ports:
  - port: 6767
    protocol: TCP
  selector:
    app: bazarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-claim
      containers:
      - env:
        - name: TZ
          value: {{ .Values.Timezone }}
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        resources:
          limits:
            cpu: '1'
            memory: 250Mi
        image: linuxserver/bazarr:{{ .Values.bazarr.version }}
        name: bazarr
        volumeMounts:
          - mountPath: /config
            name: bazarr-config
        ports:
        - containerPort: 6767
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: bazarr-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config
  labels:
    type: local
    name: bazarr-config
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/home-media-server/bazarr/config
    type: DirectoryOrCreate
