apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.storage.host.dir }}/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi