apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.host.config.capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.storage.host.config.dir }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.host.config.capacity }}