apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.host.media.capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.storage.host.media.dir }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.host.media.capacity }}