apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
      - path: /radarr
        pathType: Prefix
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
      - path: /sonarr
        pathType: Prefix
        backend:
          service:
            name: sonarr-service
            port:
              number: 8989
      - path: /bazarr
        pathType: Prefix
        backend:
          service:
            name: bazarr-service
            port:
              number: 6767
      - path: /prowlarr
        pathType: Prefix
        backend:
          service:
            name: prowlarr-service
            port:
              number: 9117
      - path: /transmission
        pathType: Prefix
        backend:
          service:
            name: transmissionopenvpn-service
            port:
              number: 9091
      - path: /jellyfin
        pathType: Prefix
        backend:
          service:
            name: jellyfin-tcp-service
            port:
              number: 8096
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heimdall-service
            port:
              number: 80