apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /radarr
        pathType: Prefix
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
      - path: /radarr/api
        pathType: Prefix
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
      - path: /sonarr
        pathType: Prefix
        backend:
          service:
            name: sonarr-service
            port:
              number: 8989
      - path: /sonarr/api
        pathType: Prefix
        backend:
          service:
            name: sonarr-service
            port:
              number: 8989
      - path: /bazarr
        pathType: Prefix
        backend:
          service:
            name: bazarr-service
            port:
              number: 6767
      - path: /bazarr/api
        pathType: Prefix
        backend:
          service:
            name: bazarr-service
            port:
              number: 6767
      - path: /jackett
        pathType: Prefix
        backend:
          service:
            name: jackett-service
            port:
              number: 9117
      - path: /jackett/api
        pathType: Prefix
        backend:
          service:
            name: jackett-service
            port:
              number: 9117
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heimdall-service
            port:
              number: 80