bazarr:
  clusterIP: 10.43.163.13
  image:
    repository: linuxserver/bazarr
    tag: '1.4.2'
    registry: lscr.io
    pullPolicy: Always

cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: '2024.4.0'
    registry: docker.io
    pullPolicy: Always

heimdall:
  clusterIP: 10.43.181.121
  image:
    repository: linuxserver/heimdall
    tag: '2.6.1'
    registry: lscr.io
    pullPolicy: Always

jellyfin:
  clusterIP: 10.43.18.241
  image:
    repository: linuxserver/jellyfin
    tag: '10.8.11'
    registry: lscr.io
    pullPolicy: Always

prowlarr:
  clusterIP: 10.43.22.107
  flaresolverr:
    image:
      repository: flaresolverr/flaresolverr
      tag: latest
      registry: ghcr.io
      pullPolicy: Always
  image:
    repository: linuxserver/prowlarr
    tag: '1.9.4'
    registry: lscr.io
    pullPolicy: Always

radarr:
  clusterIP: 10.43.231.196
  image:
    repository: linuxserver/radarr
    tag: '5.0.3'
    registry: lscr.io
    pullPolicy: Always

sonarr:
  clusterIP: 10.43.26.211
  image:
    repository: linuxserver/sonarr
    tag: '4.0.4'
    registry: lscr.io
    pullPolicy: Always

transmissionopenvpn:
  clusterIP: 10.43.26.112
  image:
    repository: haugene/transmission-openvpn
    tag: '5.3'
    registry: docker.io
    pullPolicy: Always

calibre:
  clusterIP: 10.43.35.158
  nginx:
    image:
      repository: nginx
      tag: latest
      registry: docker.io
      pullPolicy: Always
  web:
    image:
      repository: linuxserver/calibre-web
      tag: latest
      registry: lscr.io
      pullPolicy: Always

homeassistant:
  clusterIP: 10.43.178.128
  image:
    repository: home-assistant/home-assistant
    tag: '2023.12'
    registry: ghcr.io
    pullPolicy: Always

readarr:
  clusterIP: 10.43.253.24
  image:
    repository: linuxserver/readarr
    tag: nightly
    registry: lscr.io
    pullPolicy: Always

nvidia-device-plugin:
  gfd:
    enabled: true