bazarr:
  image:
    repository: linuxserver/bazarr
    tag: '1.4.0'
    registry: lscr.io
    pullPolicy: Always

cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: '2024.1.2'
    registry: docker.io
    pullPolicy: Always

heimdall:
  image:
    repository: linuxserver/heimdall
    tag: '2.5.8'
    registry: lscr.io
    pullPolicy: Always

jellyfin:
  image:
    repository: linuxserver/jellyfin
    tag: '10.8.11'
    registry: lscr.io
    pullPolicy: Always

prowlarr:
  image:
    repository: linuxserver/prowlarr
    tag: '1.9.4'
    registry: lscr.io
    pullPolicy: Always

radarr:
  image:
    repository: linuxserver/radarr
    tag: '5.0.3'
    registry: lscr.io
    pullPolicy: Always

sonarr:
  image:
    repository: linuxserver/sonarr
    tag: '4.0.0'
    registry: lscr.io
    pullPolicy: Always

transmissionopenvpn:
  image:
    repository: haugene/transmission-openvpn
    tag: '5.3'
    registry: docker.io
    pullPolicy: Always

nvidia-device-plugin:
  image:
    repository: registry.gitlab.com/nvidia/kubernetes/device-plugin/staging/k8s-device-plugin
    tag: "8b416016"
  gfd:
    enabled: true