bazarr:
  image:
    repository: linuxserver/bazarr
    tag: '1.4.2'
    registry: lscr.io
    pullPolicy: Always

cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: '2024.3.0'
    registry: docker.io
    pullPolicy: Always

heimdall:
  image:
    repository: linuxserver/heimdall
    tag: '2.6.1'
    registry: lscr.io
    pullPolicy: Always

jellyfin:
  image:
    repository: linuxserver/jellyfin
    tag: '10.8.11'
    registry: lscr.io
    pullPolicy: Always

prowlarr:
  image:
    repository: linuxserver/prowlarr
    tag: '1.9.4'
    registry: lscr.io
    pullPolicy: Always

radarr:
  image:
    repository: linuxserver/radarr
    tag: '5.0.3'
    registry: lscr.io
    pullPolicy: Always

sonarr:
  image:
    repository: linuxserver/sonarr
    tag: '4.0.3'
    registry: lscr.io
    pullPolicy: Always

transmissionopenvpn:
  image:
    repository: haugene/transmission-openvpn
    tag: '5.3'
    registry: docker.io
    pullPolicy: Always

flaresolverr:
  image:
    repository: flaresolverr/flaresolverr
    tag: latest
    registry: ghcr.io
    pullPolicy: Always

calibre:
  image:
    repository: linuxserver/calibre
    tag: v4
    registry: lscr.io
    pullPolicy: Always

calibreweb:
  image:
    repository: linuxserver/calibre-web
    tag: latest
    registry: lscr.io
    pullPolicy: Always

readarr:
  image:
    repository: linuxserver/readarr
    tag: nightly
    registry: lscr.io
    pullPolicy: Always

nginx:
  image:
    repository: nginx
    tag: latest
    registry: docker.io
    pullPolicy: Always

nvidia-device-plugin:
  gfd:
    enabled: true