bazarr:
  clusterIP: 10.43.163.13
  image:
    repository: linuxserver/bazarr
    tag: '1.4.5'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 6767

cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: '2024.10.1'
    registry: docker.io
    pullPolicy: Always

heimdall:
  clusterIP: 10.43.181.121
  image:
    repository: linuxserver/heimdall
    tag: '2.6.1'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 80

jellyfin:
  clusterIP: 10.43.18.241
  image:
    repository: linuxserver/jellyfin
    tag: '10.9.11'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http:
      cluster: 8096
      node: 30096
    https:
      cluster: 8920
      node: 30097
    autoDiscovery:
      standard:
        cluster: 7359
        node: 30098
      service:
        cluster: 1900
        node: 30099

prowlarr:
  clusterIP: 10.43.22.107
  flaresolverr:
    image:
      repository: flaresolverr/flaresolverr
      tag: latest
      registry: ghcr.io
      pullPolicy: Always
    ports:
      http: 8191
  image:
    repository: linuxserver/prowlarr
    tag: '1.25.4'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 9696

radarr:
  clusterIP: 10.43.231.196
  image:
    repository: linuxserver/radarr
    tag: '5.12.2'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 7878

sonarr:
  clusterIP: 10.43.26.211
  image:
    repository: linuxserver/sonarr
    tag: '4.0.10'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 8989

transmissionopenvpn:
  clusterIP: 10.43.26.112
  image:
    repository: haugene/transmission-openvpn
    tag: '5.3'
    registry: docker.io
    pullPolicy: Always
  ports:
    http: 9091

calibre:
  clusterIP: 10.43.35.158
  nginx:
    image:
      repository: nginx
      tag: latest
      registry: docker.io
      pullPolicy: Always
    ports:
      http: 80
  web:
    image:
      repository: linuxserver/calibre-web
      tag: latest
      registry: lscr.io
      pullPolicy: Always
    ports:
      http: 8083

homeassistant:
  clusterIP: 10.43.178.128
  image:
    repository: home-assistant/home-assistant
    tag: '2024.10'
    registry: ghcr.io
    pullPolicy: Always
  ports:
    http: 8123

readarr:
  clusterIP: 10.43.253.24
  image:
    repository: linuxserver/readarr
    tag: nightly
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 8787

# nvidia-device-plugin:
#   gfd:
#     enabled: false