bazarr:
  clusterIP: 10.43.163.13
  image:
    repository: linuxserver/bazarr
    tag: '1.5.2'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 6767

cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: '2025.8.1'
    registry: docker.io
    pullPolicy: Always

heimdall:
  clusterIP: 10.43.181.121
  image:
    repository: linuxserver/heimdall
    tag: '2.7.5'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 80

jellyfin:
  clusterIP: 10.43.18.241
  image:
    repository: linuxserver/jellyfin
    tag: '10.10.7'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http:
      cluster: 8096
      node: 30096
    https:
      cluster: 8920
      node: 30097
    autoDiscovery:
      standard:
        cluster: 7359
        node: 30098
      service:
        cluster: 1900
        node: 30099

prowlarr:
  clusterIP: 10.43.22.107
  flaresolverr:
    image:
      repository: flaresolverr/flaresolverr
      tag: latest
      registry: ghcr.io
      pullPolicy: Always
    ports:
      http: 8191
  image:
    repository: linuxserver/prowlarr
    tag: '2.0.5'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 9696

radarr:
  clusterIP: 10.43.231.196
  image:
    repository: linuxserver/radarr
    tag: '5.27.5'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 7878

sonarr:
  clusterIP: 10.43.26.211
  image:
    repository: linuxserver/sonarr
    tag: '4.0.15'
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 8989

calibre:
  clusterIP: 10.43.35.158
  nginx:
    image:
      repository: nginx
      tag: latest
      registry: docker.io
      pullPolicy: Always
    ports:
      http: 80
  web:
    image:
      repository: linuxserver/calibre-web
      tag: latest
      registry: lscr.io
      pullPolicy: Always
    ports:
      http: 8083

homeassistant:
  clusterIP: 10.43.178.128
  image:
    repository: home-assistant/home-assistant
    tag: '2025.9'
    registry: ghcr.io
    pullPolicy: Always
  ports:
    http: 8123

gluetun:
  clusterIP: 10.43.178.129
  image:
    repository: qdm12/gluetun
    tag: latest
    registry: ghcr.io
    pullPolicy: Always
  ports:
    http: 8888
    healthcheck: 9999

transmission:
  clusterIP: 10.43.26.112
  image:
    repository: linuxserver/transmission
    tag: latest
    registry: lscr.io
    pullPolicy: Always
  ports:
    http: 9091
