name: Home Media Server CI

on:
  - pull_request

env:
  tag: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

jobs:
  helm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Start dev container
        run: devcontainer up --workspace-folder .

      - name: Check dependencies
        run: devcontainer exec --workspace-folder . -- task dependencies:check

      - name: Check environment
        run: devcontainer exec --workspace-folder . -- task environment:check

      - name: Check helm dependency compatability
        run: devcontainer exec --workspace-folder . -- task helm:dependencies:compatability:check
  k3d-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build K3d Image
        run: docker build . --tag k3d-cuda:${{ env.tag }}
        working-directory: .k3d
