name: Home Media Server CI

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm Lint
        run: docker run --rm -v ${PWD}/helm:/mount -w /mount alpine/helm lint --values values.yaml --values sample.infrastructure.values.yaml --namespace home-media-server
